In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import math

In [4]:
Training_set = pd.read_csv("heart_disease_3features.csv")

In [5]:
Training_set.head()

age  trestbps  thalach  heart_disease
0  63.0     145.0    150.0              0
1  67.0     160.0    108.0              1
2  67.0     120.0    129.0              1
3  37.0     130.0    187.0              0
4  41.0     130.0    172.0              0

In [6]:
ts_age = np.array(Training_set["age"])
mean = np.mean(ts_age)
std = np.std(ts_age)
ts_age = ts_age - mean
ts_age = ts_age / std
ts_age

array([ 0.94872647,  1.39200191,  1.39200191, -1.93256387, -1.48928843,
        0.17299446,  0.83790761,  0.28381332,  0.94872647, -0.15946212,
        0.28381332,  0.17299446,  0.17299446, -1.15683185, -0.27028098,
        0.28381332, -0.71355642, -0.04864326, -0.71355642, -0.60273756,
        1.05954533,  0.39463218,  0.39463218,  0.39463218,  0.61626989,
       -0.4919187 ,  0.39463218,  1.28118305, -1.26765071, -1.60010729,
        1.61363963,  0.61626989,  1.05954533,  0.50545103, -1.15683185,
       -1.37846957, -1.26765071,  0.28381332,  0.0621756 ,  0.72708875,
        1.17036419, -1.60010729,  1.83527735,  0.50545103,  0.72708875,
        0.39463218, -0.38109984, -0.4919187 ,  1.17036419, -0.15946212,
       -1.48928843,  1.17036419, -1.15683185, -1.15683185,  0.61626989,
       -0.04864326, -0.4919187 , -1.48928843, -0.04864326, -0.38109984,
       -0.38109984, -0.93519414,  0.39463218, -0.04864326, -0.04864326,
        0.61626989,  0.61626989, -0.04864326,  0.50545103, -0.93

In [7]:
ts_trestbps = np.array(Training_set["trestbps"])
mean = np.mean(ts_trestbps)
std = np.std(ts_trestbps)
ts_trestbps = ts_trestbps - mean
ts_trestbps = ts_trestbps / std
ts_trestbps

array([ 0.75752504,  1.61121989, -0.6652997 , -0.0961698 , -0.0961698 ,
       -0.6652997 ,  0.47296009, -0.6652997 , -0.0961698 ,  0.47296009,
        0.47296009,  0.47296009, -0.0961698 , -0.6652997 ,  2.29417576,
        1.04208999, -1.2344296 ,  0.47296009, -0.0961698 , -0.0961698 ,
       -1.2344296 ,  1.04208999, -0.6652997 ,  0.01765618, -0.0961698 ,
       -0.6652997 , -0.6652997 ,  1.04208999,  1.04208999, -1.2344296 ,
        0.47296009, -0.83603867,  0.47296009,  0.18839514, -0.0961698 ,
        0.47296009, -0.6652997 ,  1.04208999,  0.01765618,  1.04208999,
        1.04208999,  0.47296009,  1.61121989,  1.04208999, -0.0961698 ,
       -1.12060362, -1.2344296 ,  1.04208999,  0.47296009, -0.0961698 ,
       -1.51899455, -0.6652997 , -1.12060362, -0.0961698 , -0.0961698 ,
       -0.43764774,  0.47296009, -1.2344296 , -0.38073475, -0.38073475,
       -0.0961698 ,  0.58678607, -0.20999578,  0.18839514, -0.6652997 ,
        0.75752504,  0.47296009,  1.04208999,  2.18034978,  1.04

In [8]:
ts_thalach = np.array(Training_set["thalach"])
mean = np.mean(ts_thalach)
std = np.std(ts_thalach)
ts_thalach = ts_thalach - mean
ts_thalach = ts_thalach / std
ts_thalach

array([ 0.01719733, -1.82190531, -0.90235399,  1.63735918,  0.98053681,
        1.24326576,  0.45507891,  0.58644339, -0.11416714,  0.23613812,
       -0.07037899,  0.1485618 , -0.33310794,  1.02432497,  0.54265523,
        1.06811312,  0.80538418,  0.45507891, -0.46447241,  0.93674865,
       -0.24553162,  0.54265523,  0.45507891,  1.02432497, -0.77098952,
        0.36750259,  0.98053681, -1.55917636,  0.93674865, -1.55917636,
        0.06098549,  0.45507891,  0.36750259,  0.49886707,  1.28705392,
        1.24326576, -1.29644741, -1.64675268, -0.77098952, -0.55204873,
       -1.55917636,  1.24326576,  0.54265523,  0.32371444,  0.84917233,
        0.6740197 , -1.16508294, -0.94614215,  0.32371444,  0.10477365,
        0.80538418, -0.42068425,  0.1485618 ,  1.68114734, -0.24553162,
       -1.77811715,  0.58644339,  0.36750259,  0.10477365, -1.07750662,
       -0.33310794,  0.45507891, -0.81477768,  0.89296049, -1.60296452,
       -0.33310794,  0.23613812,  0.6740197 , -0.42068425, -0.11

In [9]:
ts_target = np.array(Training_set["heart_disease"])